version: "3.7"

services:
  frontend:
    volumes:
      - type: bind
        source: ./nginx/production.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
    ports:
      - 443:443
    logging:
      driver: awslogs
      options:
        awslogs-group: log-group-todoapp
        awslogs-create-group: "true"
        awslogs-stream: log-stream-frontend
        