version: "3.7"	

services:	
  frontend:	
    logging:	
      driver: awslogs	
      options:	
        awslogs-group: log-group-todoapp	
        awslogs-create-group: "true"	
        awslogs-stream: log-stream-frontend
