version: "3.7"

volumes:
  volume-frontend-build:
    name: volume-frontend-build
    
networks:
  network-todoapp:
    external: true
    name: network-todoapp

services:
  frontend:
    environment:
      - NODE_ENV=$NODE_ENV
    image: ghcr.io/to-do-app/frontend:$TAG
    build: .
    volumes:
      - type: volume
        source: volume-frontend-build
        target: /frontend/build
    networks:
      - network-todoapp
    container_name: frontend
