version: "3.7"
    
networks:
  network-todoapp:
    external: true
    name: network-todoapp

services:
  frontend:
    environment:
      - NODE_ENV=$NODE_ENV
    image: ghcr.io/to-do-app/frontend:$TAG
    build: .
    networks:
      - network-todoapp
    ports:
      - 80:80
    container_name: frontend
    restart: unless-stopped
