name: Deploy

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: [self-hosted, "${{ github.event.client_payload.environment }}"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy containers
        env:
          NODE_ENV: ${{ github.event.client_payload.environment }}
          TAG: ${{ github.event.client_payload.tag }}
        run: |
          echo ${{ secrets.PACKAGES_ACCESS_TOKEN }} | docker login \
            ghcr.io \
            --username alvarogarciafer \
            --password-stdin
          docker-compose pull
          docker-compose up \
            --detach
          docker image prune \
            --all \
            --force
