name: Deploy

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: [self-hosted, "${{ github.event.client_payload.environment }}"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy containers
        env:
          NODE_ENV: ${{ github.event.client_payload.environment }}
          TAG: ${{ github.event.client_payload.tag }}
          HOST: frontend
          PORT: 3001
        run: |
          echo ${{ secrets.PACKAGES_ACCESS_TOKEN }} | docker login \
            ghcr.io \
            --username alvarogarciafer \
            --password-stdin
          docker-compose pull
          if [[ "${{ github.event.client_payload.environment }}" = "production" ]]; then
            docker-compose --file docker-compose.yml --file docker-compose.production.yml up \
              --detach
          else
            docker-compose up \
              --detach
          fi
          docker image prune \
            --all \
            --force
